### ISSUE TITLE
Add support of YAML configs

### ISSUE THREAD

**Issue by vladtcvs** [ericstoneking/42#56]
Reasons why I think YAML configs are good:

1) Plain text configs sometimes hard to read because different options are mixed together. For example
```
KEP                           !  Use Keplerian elements (KEP) or (RV) or FILE
PA                            !  Use Peri/Apoapsis (PA) or min alt/ecc (AE)
100.0     100.0               !  Periapsis & Apoapsis Altitude, km
400.0  2.0                    !  Min Altitude (km), Eccentricity
52.0                          !  Inclination (deg)
180.0                         !  Right Ascension of Ascending Node (deg)
0.0                           !  Argument of Periapsis (deg)
0.0                           !  True Anomaly (deg)
0.0  0.0  0.0                 !  RV Initial Position (km)
0.0  0.0  0.0                 !  RV Initial Velocity (km/sec)
```
Keplerian PA, Keplerian AE, RV, and file, all they don't separated. And you can not add line for separate them because of very strict file format

2) You can not comment-out lines. While in YAML you can do something like 

```
        Position_Velocity_Orbit_Parameters:
#            Position:   [6000, 0, 0]    # km
            Position:   [7000, 0, 0]    # km
            Velocity:   [8, 0, 0]       # km/s
```
And it's easy to switch between 6000 and 7000 variants.

Now i'm gradually adding such support
